### ISSUE TITLE
[Websocket]: Doesn't work in wasm

### ISSUE THREAD

**Issue by Milerius** [Kucoin/kucoin-go-sdk#103]
https://github.com/Kucoin/kucoin-go-sdk/blob/468026a33b3a24a4d8f7788c8b3032b3a95cb425/websocket.go#L13

Gorilla websocket doesn't support wasm build, is it possible to use one that support it ? such as https://github.com/nhooyr/websocket (btw it's more efficient and more robust)

**Comment by codewc** [comment]
> https://github.com/Kucoin/kucoin-go-sdk/blob/468026a33b3a24a4d8f7788c8b3032b3a95cb425/websocket.go#L13
> 
> Gorilla websocket doesn't support wasm build, is it possible to use one that support it ? such as https://github.com/nhooyr/websocket (btw it's more efficient and more robust)

How did you build it?
We need to research and test it.

**Comment by iamalanal** [comment]
Is the issue solved?

**Comment by ISAAC-XXYYZZ** [comment]
Since Gorilla doesn't support WebAssembly, our SDK won't support it either. However, why not try using the NodeJS SDK? Please refer to it here. https://github.com/Kucoin/kucoin-node-sdk
