### ISSUE TITLE
missing "minFunds" in SymbolModel

### ISSUE THREAD

**Issue by cj60205** [Kucoin/kucoin-go-sdk#123]
The field "minFunds" is listed in document (https://docs.kucoin.com/#get-symbols-list).
But, there is not found in SymbolModel
https://github.com/Kucoin/kucoin-go-sdk/blob/master/symbol.go#L8

**Comment by iamalanal** [comment]
Is the issue solved?

**Comment by ISAAC-XXYYZZ** [comment]
Please use SymbolModelV2. For details, refer to our documentation: https://www.kucoin.com/docs/rest/spot-trading/market-data/get-symbols-list
