### ISSUE TITLE
context.Context parameter missing from methods

### ISSUE THREAD

**Issue by vniche** [Kucoin/kucoin-go-sdk#124]
All methods that spawns a request to a remote service/API or have an inter process communication should (it is strongly recommended for reliability) have a `context.Context` as a parameters (preferably the first one). Golang [context package overview](https://pkg.go.dev/context#pkg-overview):

> Package context defines the Context type, which carries deadlines, cancellation signals, and other request-scoped values across API boundaries and between processes.

For example:

```
import (
    "context"
    "time"
  
    "github.com/Kucoin/kucoin-go-sdk"
)

kucoinClient := kucoin.NewApiService()

ctx, cancel := context.WithTimeout(context.Background, 5 * time.Second)
defer cancel()

_, _ = kucoinClient.Accounts(ctx, "", "")

_, _ = kucoinClient.Prices(ctx, "", "")
```

That way, if the context is canceled by either client or server (due to timeout - client-defined or gateway-defined - for example) such behavior is propagated throughout all peers.

**Comment by iamalanal** [comment]
Is the issue solved?

**Comment by ISAAC-XXYYZZ** [comment]
Thank you for your suggestion. This is indeed a great idea. We will include this feature in future API iterations. Let's stay in touch.
