### ISSUE TITLE
Empty order list 

### ISSUE THREAD

**Issue by libinthomas-kv** [Kucoin/kucoin-go-sdk#125]
I'm trying to pull my Kucoin transactions using this SDK. I'm getting transactions for deposits and withdrawals, even order by id is also working, but order list API is not working. Always getting empty array as a response

**Comment by Mreyna3** [comment]
Did you happen to ever find the reason for this, I too am experiencing this

**Comment by libinthomas-kv** [comment]
@Mreyna3 Try using the Fills API, you will be able to fetch the last 9 months transactions. The order list provides the list of current  open orders only.

**Comment by iamalanal** [comment]
Is the issue solved?

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
