### ISSUE TITLE
Missing field "chain" in ChainsModel

### ISSUE THREAD

**Issue by arturalbov** [Kucoin/kucoin-go-sdk#128]
The field "chain" is listed in [api docs](https://docs.kucoin.com/#get-currency-detail-recommend). Though there is no such field in current [ChainsModel](https://github.com/Kucoin/kucoin-go-sdk/blob/master/currency.go)

**Comment by fenzheng1991** [comment]
will fix soon!

**Comment by fenzheng1991** [comment]
done
